# Generated by Django 4.0.4 on 2022-05-11 15:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_article_author_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
