# Generated by Django 4.0.4 on 2022-05-14 20:26

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_article_created_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.author', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.category', verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(null=True, verbose_name='Utworzone'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author',
            field=models.CharField(max_length=64, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=64, verbose_name='Kategoria'),
        ),
    ]
