# Generated by Django 4.0.4 on 2022-05-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_article_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(null=True, verbose_name='Utworzone'),
        ),
    ]
